import { DiscogsArtist, DiscogsFormat, DiscogsLabel, DiscogsReleaseResponse } from "../discogs/types"

function processArtistsOrLabels(input: DiscogsArtist[] | DiscogsLabel[]): string {
    const names = input.map((x) => x.name.split(" (")[0])

    return [...new Set(names)].join(" / ")
}

function processCatNumbers(input: DiscogsLabel[]): string {
    const names = input.map((x) => x.catno.split(" (")[0])

    return [...new Set(names)].join(", ")
}

function processFormats(input: DiscogsFormat[]): string {
    const result: string[] = []

    const names = input.map((x) => x.name)

    const cdCounter = names.filter(x => x === "CD").length
    const dvdCounter = names.filter(x => x === "DVD").length

    if (cdCounter === 1) { result.push("CD") } else if (cdCounter > 1) { result.push(`${cdCounter}CD`) }
    if (dvdCounter === 1) { result.push("DVD") } else if (dvdCounter > 1) { result.push(`${dvdCounter}DVD`) }

    result.push(...names.filter(x => x !== "CD" && x !== "DVD"))

    return result.join(", ")
}

export async function processRelease(data: DiscogsReleaseResponse) {
    const release = {
        discogs_id: data.id,
        master_id: data.master_id,
        uri: data.uri,
        title: data.title,
        artist: processArtistsOrLabels(data.artists),
        artist_id: data.artists.map((artist) => artist.id), // it's a list!
        year: data.year,
        release_date: data.released,
        country: data.country,
        genres: data.genres,
        styles: data.styles,
        formats: processFormats(data.formats),
        labels: processArtistsOrLabels(data.labels),
        catalog_number: processCatNumbers(data.labels),
        tracklist: data.tracklist, // json
        identifiers: data.identifiers, // json
        thumb: data.thumb,
        images: data.images, // json
        have: data.community.have,
        want: data.community.want,
        notes: data.notes,
        date_added: data.date_added,
        blocked_from_sale: data.blocked_from_sale,
        is_offensive: data.is_offensive,
    }

    return release
}




//[
//	["...And Oceans", "Bloodthorn"],
//	["Abscess (2)", "Bloodred Bacteria"],
//	["Abscess (2)", "Bonesaw (3)"],
//	["Abscess (2)", "Population Reduction"],
//	["Amatory", "Spermadonarz"],
//	["Angra", "Edguy", "Freedom Call"],
//	["Antaios", "Der Gerwelt"],
//	["Antigama", "The Kill", "Noisear"],
//	["Arcturus (2)", "The Deception Circus"],
//	["Arcturus (2)", "The Deception Circus"],
//	["Ashen Light", "Divizion S-187"],
//	["Asphyx (2)", "Hooded Menace"],
//	["Asphyx (2)", "Hooded Menace"],
//	["Asphyx (2)", "Thanatos (4)"],
//	["Autopsy (2)", "Bloodbath"],
//	["Ayreon", "Tobias Sammet's Avantasia"],
//	["Ayreon", "Tobias Sammet's Avantasia"],
//	["Bathory", "Tankard", "Rage (6)"],
//	["Blood (5)", "Impetigo"],
//	["Blood (5)", "Incantation"],
//	["Blood Duster", "Brutal Truth"],
//	["Blood Red Fog", "Cosmic Church"],
//	["Blood Red Fog", "Musta Kappeli"],
//	["Bongripper", "Conan (6)"],
//	["Bradi Cerebri Ectomia", "Methadone Abortion Clinic", "Septicopyemia", "Fecal Body Incorporated"],
//	["Brutal Truth", "Bastard Noise"],
//	["Brutality Reigns Supreme", "Gruesome Stuff Relish"],
//	["Burzum", "Uruk-Hai (4)"],
//	["Carnage (4)", "Cadaver"],
//	["Cliteater", "The Day Everything Became Nothing"],
//	["Coalesce", "Napalm Death"],
//	["Cock And Ball Torture", "Disgorge (2)"],
//	["Cock And Ball Torture", "Last Days Of Humanity"],
//	["Cock And Ball Torture", "Last Days Of Humanity"],
//	["Conan (6)", "Deadsmoke"],
//	["Cosmic Psychos", "Zeke"],
//	["Cuntgrinder", "Satan's Revenge On Mankind", "Hymen Holocaust"],
//	["Dark Funeral", "Infernal (5)"],
//	["Dead Infection", "Haemorrhage"],
//	["Deep Purple", "Royal Philharmonic Orchestra", "Malcolm Arnold"],
//	["Deep Purple", "Royal Philharmonic Orchestra", "Malcolm Arnold"],
//	["Deep Purple", "Royal Philharmonic Orchestra", "Malcolm Arnold"],
//	["Deep Purple", "Royal Philharmonic Orchestra", "Malcolm Arnold"],
//	["Depression", "Haemorrhage"],
//	["Der Gerwelt", "Nargathrond"],
//	["Discharge", "G.B.H.", "The Exploited"],
//	["Drudkh", "Hades Almighty"],
//	["Earth (2)", "K.K. Null"],
//	["Electric Wizard (2)", "Orange Goblin"],
//	["Elton John", "Tim Rice", "Hans Zimmer"],
//	["Emperor (2)", "Enslaved"],
//	["Frank Klepacki", "Jarrid Mendelson"],
//	["Frank Klepacki", "Jarrid Mendelson"],
//	["Frank Klepacki", "Jarrid Mendelson"],
//	["Freddie Mercury", "Montserrat Caballé"],
//	["From The Bogs Of Aughiska", "Dark Ages (2)"],
//	["Fuck... I'm Dead", "Engorged"],
//	["Goatsnake", "Burning Witch"],
//	["Gorguts", "Disincarnate"],
//	["Gustav Holst", "Charles Dutoit", "Orchestre symphonique de Montréal"],
//	["Gustav Holst", "Orchestre symphonique de Montréal", "Charles Dutoit"],
//	["Haemorrhage", "Dead (2)"],
//	["Haemorrhage", "Denak"],
//	["Haemorrhage", "Disgorge (2)"],
//	["Haemorrhage", "Gruesome Stuff Relish"],
//	["Haemorrhage", "Hemdale", "Meat Spreader"],
//	["Haemorrhage", "Impaled"],
//	["HammerFall", "Edguy"],
//	["Herbarium", "Old Silver Key"],
//	["Hymen Holocaust", "Bloodbastard"],
//	["I Abhor", "Wormrot"],
//	["I Abhor", "Wormrot"],
//	["Iancu Dumitrescu", "Ana-Maria Avram", "Stephen O'Malley"],
//	["Iced Earth", "Type O Negative", "Engel (4)"],
//	["Iggy Pop", "James Williamson"],
//	["Iggy Pop", "James Williamson"],
//	["Ildjarn", "Hate Forest"],
//	["Impaled Nazarene", "Driller Killer"],
//	["Impetigo", "Ingrowing"],
//	["Inon Zur", "Jeremy Soule"],
//	["Iron Maiden", "Bruce Dickinson"],
//	["Jan Dargatz", "Gary Rhodes (2)"],
//	["Jello Biafra", "Melvins"],
//	["Jello Biafra", "Melvins"],
//	["Jimmy Cliff", "Lebo M"],
//	["Jimmy Cliff", "Lebo M"],
//	["Judas Priest", "Ozzy Osbourne"],
//	["Kelly Osbourne", "Ozzy Osbourne"],
//	["Khost", "Godflesh"],
//	["King Diamond (2)", "Black Rose (4)"],
//	["King Diamond", "Mercyful Fate"],
//	["King Diamond", "Mercyful Fate"],
//	["Kiss", "Ace Frehley"],
//	["Kiss", "Ace Frehley"],
//	["Kiss", "Ace Frehley"],
//	["Kiss", "Gene Simmons"],
//	["Kiss", "Gene Simmons"],
//	["Kiss", "Gene Simmons"],
//	["Kiss", "Paul Stanley"],
//	["Kiss", "Paul Stanley"],
//	["Kiss", "Peter Criss"],
//	["Kiss", "Peter Criss"],
//	["Kiss", "Peter Criss"],
//	["Kreator", "Sodom", "Destruction", "Tankard"],
//	["Lingua Mortis Orchestra", "Rage (6)"],
//	["Lita Ford", "Ozzy Osbourne"],
//	["Machetazo", "Abscess (2)"],
//	["Marcel Cellier", "Le Mystère Des Voix Bulgares"],
//	["Marcel Cellier", "Le Mystère Des Voix Bulgares"],
//	["Marcel Cellier", "Le Mystère Des Voix Bulgares"],
//	["Marcel Cellier", "Le Mystère Des Voix Bulgares"],
//	["Marja Mattlar", "Anton Belov"],
//	["Mayhem", "Zyklon-B"],
//	["Melvins", "Lustmord"],
//	["Melvins", "Napalm Death"],
//	["Metallica", "San Francisco Symphony"],
//	["Metallica", "Michael Kamen", "San Francisco Symphony"],
//	["Metallica", "Michael Kamen", "San Francisco Symphony"],
//	["Metallica", "Michael Kamen", "San Francisco Symphony"],
//	["Metallica", "Michael Kamen", "San Francisco Symphony"],
//	["Metallica", "Michael Kamen", "San Francisco Symphony"],
//	["Mike Kunka", "Melvins"],
//	["Morbid", "Mayhem"],
//	["Morbid", "Mayhem"],
//	["Mortician", "Fleshgrind"],
//	["Necro Tampon", "The Creatures From The Tomb", "Hymen Holocaust"],
//	["Necromantia", "Acherontas"],
//	["Necromantia", "Varathron"],
//	["Necromantia", "Varathron"],
//	["Necromantia", "Varathron"],
//	["Nightwish", "Jonsu"],
//	["Nightwish", "Jonsu"],
//	["Nokturnal Mortum", "Graveland"],
//	["Opeth", "Enslaved"],
//	["Oren Ambarchi", "Stephen O'Malley", "Randall Dunn"],
//	["Ozzy Osbourne", "Type O Negative"],
//	["Pyphomgertum", "Dawn (8)"],
//	["Queen", "David Bowie"],
//	["Queen", "David Bowie"],
//	["Queen", "David Bowie"],
//	["Queen", "David Bowie"],
//	["Queen", "Paul Rodgers"],
//	["Queen", "Paul Rodgers"],
//	["Rage (6)", "Lingua Mortis Orchestra"],
//	["Rage (6)", "Lingua Mortis Orchestra"],
//	["Rage (6)", "Lingua Mortis Orchestra"],
//	["Rage (6)", "The Prague Symphony Orchestra"],
//	["Rage (6)", "Lingua Mortis Orchestra"],
//	["Rage (6)", "Lingua Mortis"],
//	["Rage (6)", "Lingua Mortis Orchestra"],
//	["Rage (6)", "Lingua Mortis Orchestra"],
//	["Redd Kross", "Sonic Youth", "Carpenters"],
//	["Rhapsody", "Christopher Lee"],
//	["Richard Strauss", "Carl Maria von Weber", "Hermann Baumann", "Gewandhausorchester Leipzig", "Kurt Masur"],
//	["Royal Philharmonic Orchestra", "Mike Oldfield"],
//	["Royal Philharmonic Orchestra", "Mike Oldfield", "David Bedford"],
//	["Royal Philharmonic Orchestra", "Mike Oldfield", "David Bedford"],
//	["Running Wild", "Hellhammer (2)", "Helloween", "Dark Avenger (2)"],
//	["Satyricon", "Enslaved"],
//	["Satyricon", "Enslaved"],
//	["Satyricon", "Den Norske Operas Kor"],
//	["Satyricon", "Den Norske Operas Kor"],
//	["Septicopyemia", "Formalin (2)"],
//	["Skullhog", "Violation Wound"],
//	["Skyclad", "Lemming Project"],
//	["Sodom", "Running Wild"],
//	["Sodom", "Running Wild"],
//	["Sonic Youth", "Carpenters", "Matthew Sweet"],
//	["Sonic Youth", "Yamatsuka Eye"],
//	["Squash Bowels", "Disgorge (2)"],
//	["St. Francis Duo", "Stephen O'Malley", "Steve Noble"],
//	["Stephen O'Malley", "Attila Csihar"],
//	["Stephen O'Malley", "Z'EV"],
//	["Stephen O'Malley", "Anthony Pateras"],
//	["Sunn O)))", "Boris (3)"],
//	["Sunn O)))", "Earth (2)"],
//	["Sunn O)))", "Ulver"],
//	["Supersuckers", "Zeke"],
//	["Swans", "Michael Gira"],
//	["The Angels Of Light", "Akron/Family"],
//	["The Body Lovers", "The Body Haters"],
//	["The Body Lovers", "The Body Haters"],
//	["The Body Lovers", "The Body Haters"],
//	["The Bug", "Earth (2)"],
//	["The Lord (2)", "Petra Haden"],
//	["Thrones", "Sedan (3)"],
//	["Tony Iommi", "Tony Iommi", "Glenn Hughes", "Glenn Hughes"],
//	["Tony Iommi", "Glenn Hughes"],
//	["Tony Iommi", "Glenn Hughes"],
//	["Tony Iommi", "Glenn Hughes"],
//	["Tony Iommi", "Glenn Hughes"],
//	["Turisas", "Norther"],
//	["Týr", "The Symphony Orchestra Of The Faroe Islands"],
//	["Venomous Concept", "Blood Duster"],
//	["Verge (3)", "Blood Red Fog"],
//	["Zeke", "Disfear"],
//	["Андрей Машнин", "никого нет дома", "Vizantijsky Art Punk Ansambl'", "Кузьма И Виртуозы", "Сергей Летов"],
//	["Евгений Чичерин", "Хмели-Сунели"],
//	["Евгений Чичерин", "Хмели-Сунели"],
//	["Егор Летов", "Сергей Летов"],
//	["Егор Летов", "Сергей Летов"],
//	["Манагер", "Егор Летов"],
//	["Наталия Медведева", "Сергей Высокосов"],
//	["Сергей Высокосов", "НИЛ-62"],
//	["Сергей Высокосов", "НИЛ-62"],
//	["Янка", "Гражданская Оборона"]
//]
